# Generated by Django 3.1.7 on 2023-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220319_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_tb_jobfair',
            name='resume',
            field=models.FileField(null='empty', upload_to='pinnacle/employe_resume'),
        ),
        migrations.AlterField(
            model_name='employer_tb_jobfair',
            name='job_file',
            field=models.FileField(null='empty', upload_to='pinnacle/employer_file'),
        ),
    ]
